### ISSUE TITLE
[Feature Suggestion} Input

### ISSUE THREAD

**Issue by etherealxx** [face-hh/bussin#10]
Was about to make a simple game with this, but just realized that there's no way for user to have input.
I don't know how hard it would be to add that, this project itself is already lookin hard.
Just a simple int/char input would be nice.
Really appreciated if it'll be added, but also understandable if not.

**Comment by Polygons1** [comment]
adding that rn to my fork

**Comment by face-hh** [comment]
> Was about to make a simple game with this, but just realized that there's no way for user to have input. I don't know how hard it would be to add that, this project itself is already lookin hard. Just a simple int/char input would be nice. Really appreciated if it'll be added, but also understandable if not.

I managed to get a somewhat working function for it, although it's disconnected from the terminal APIs and therefore only displays the question without showing what the user is typing (visually).

It will be added in the next version as `yap` (bsx) or `input` (bs).

**Comment by face-hh** [comment]
Added in 25b992a
