### ISSUE TITLE
Bye..

### ISSUE THREAD

**Issue by Polygons1** [face-hh/bussin#11]
Bye @everyone, I am moving away from this repo, and continuing developing on my fork, see y'all there!

**Comment by KaseyTheJackal** [comment]
Imagine attempting to mention everyone on Github

**Comment by danriedl** [comment]
What is lil bro yapping about fr 💀

**Comment by Polygons1** [comment]
> Imagine attempting to mention everyone on Github

jokes on you, it's actually works :joy:

**Comment by KaseyTheJackal** [comment]
> > Imagine attempting to mention everyone on Github
> 
> jokes on you, it's actually works 😂

No, actually, no it doesn't. You're mentioning an account that's inactive and owned by a company

**Comment by Polygons1** [comment]
> What is lil bro yapping about fr 💀

I am making my own version because <@778518819055861761> hates my PR

**Comment by Polygons1** [comment]
> > > Imagine attempting to mention everyone on Github
> > 
> > 
> > jokes on you, it's actually works 😂
> 
> No, actually, no it doesn't. You're mentioning an account that's inactive and owned by a company

look at the discord :skull:

**Comment by KaseyTheJackal** [comment]
> > > > Imagine attempting to mention everyone on Github
> > > 
> > > 
> > > jokes on you, it's actually works 😂
> > 
> > 
> > No, actually, no it doesn't. You're mentioning an account that's inactive and owned by a company
> 
> look at the discord 💀

Honestly L tbh

**Comment by Polygons1** [comment]
> > > > > Imagine attempting to mention everyone on Github
> > > > 
> > > > 
> > > > jokes on you, it's actually works 😂
> > > 
> > > 
> > > No, actually, no it doesn't. You're mentioning an account that's inactive and owned by a company
> > 
> > 
> > look at the discord 💀
> 
> Honestly L tbh

wdym?

**Comment by KaseyTheJackal** [comment]
> > What is lil bro yapping about fr 💀
> 
> I am making my own version because <@778518819055861761> hates my PR

Because it's not constructive and makes some pretty bad decisions

**Comment by Polygons1** [comment]
> > > What is lil bro yapping about fr 💀
> > 
> > 
> > I am making my own version because <@778518819055861761> hates my PR
> 
> Because it's not constructive and makes some pretty bad decisions

???

**Comment by KaseyTheJackal** [comment]
> > > > > > Imagine attempting to mention everyone on Github
> > > > > 
> > > > > 
> > > > > jokes on you, it's actually works 😂
> > > > 
> > > > 
> > > > No, actually, no it doesn't. You're mentioning an account that's inactive and owned by a company
> > > 
> > > 
> > > look at the discord 💀
> > 
> > 
> > Honestly L tbh
> 
> wdym?

You give off script kiddie vibes honestly lmao

**Comment by Polygons1** [comment]
> > > > > > > Imagine attempting to mention everyone on Github
> > > > > > 
> > > > > > 
> > > > > > jokes on you, it's actually works 😂
> > > > > 
> > > > > 
> > > > > No, actually, no it doesn't. You're mentioning an account that's inactive and owned by a company
> > > > 
> > > > 
> > > > look at the discord 💀
> > > 
> > > 
> > > Honestly L tbh
> > 
> > 
> > wdym?
> 
> You give off script kiddie vibes honestly lmao

??? btw I am working now on stdin (:

**Comment by Symmettry** [comment]
script kiddie 💀

**Comment by Polygons1** [comment]
I want to make this clear, I am doing this only to myself, because I think this needs more things like built in http requests or errors

also, an executable is coming soon
