### ISSUE TITLE
Types in function parameters are not supported

### ISSUE THREAD

**Issue by hcwf** [face-hh/bussin#14]
![Alt text](https://i.kym-cdn.com/photos/images/newsfeed/002/369/918/dee.gif "a title")

Example:
`bruh test(num: x) {}`
produces this parser error:
`Parser error:
 Missing closing parenthesis inside args list { value: ':', type: 12 } Expecting:  16`
 
 Apparently the "type" is not removed from function parameters when defining a function or when trying to run a valid function with a typed argument.

**Comment by face-hh** [comment]
We, at Bussin X, do not wish to associate with our inferior competitors.

To reference a type in Bussin X, you can use the following syntax:
```diff
- bruh test(num: x) {}
+ bruh test(x: number) {}
```

Why? The regex is `: number`, not `number :`.
