### ISSUE TITLE
Numbers in variable names throw parser error

### ISSUE THREAD

**Issue by hcwf** [face-hh/bussin#16]
Example:
`lit num2 be 1 rn`

Error:
`Parser error:
 Expected equals token following identifier in var declaration. { value: '2', type: 0 } Expecting:  10`
 

Writing is tedious, I propose making this a feature so we don't have to write out the full number for each of our similarly named variables.

**Comment by face-hh** [comment]
This should be a fairly simple modification of the regex that detects alphabetic characters in the lexer. I will make sure to include support for this in the next release.

**Comment by 0x408** [comment]
fixed this issue in my commit :)
