### ISSUE TITLE
input() doesn't display text and cannot be exited with ctrl+c

### ISSUE THREAD

**Issue by Symmettry** [face-hh/bussin#25]
do any sort of input

input("aaaa")

then just press ctrl+c and it will hang until you close the terminal.

**Comment by Symmettry** [comment]
oh apparently any typing at all hangs indefinitely ??

**Comment by face-hh** [comment]
> do any sort of input
> 
> input("aaaa")
> 
> then just press ctrl+c and it will hang until you close the terminal.

Might just be dumb here, but I have no idea how to fix that 😆, rarely worked with terminal stuff such as readline

**Comment by Symmettry** [comment]
from the research i've looked at, it appears that there is an issue with readline-sync. Unsure how you could fix this then.

**Comment by Symmettry** [comment]
made title more clear with the real problem

**Comment by GStudiosX2** [comment]
All the readline libraries suck and there's no good way to read console input in node

**Comment by Symmettry** [comment]
Not a readline problem; readline works fine. It doesn't work in bussin probably due to the synchronous.

I have implemented an async fetch(). i should be able to do the same with input()

**Comment by Symmettry** [comment]
Ye should be fixed in #55

**Comment by GStudiosX2** [comment]
> Not a readline problem; readline works fine. It doesn't work in bussin probably due to the synchronous.
> 
> I have implemented an async fetch(). i should be able to do the same with input()

What causes it to not work though?

**Comment by Symmettry** [comment]
"readline-sync" does not work in the bussin environment, so we have to use "readline/promises" instead
