### ISSUE TITLE
how To Install and use?

### ISSUE THREAD

**Issue by zipcord24** [face-hh/bussin#29]
how To Install and use?

**Comment by face-hh** [comment]
Clone the repo, install NodeJS, run "npm run bussin <file>"

**Comment by zipcord24** [comment]
i'm getting this error?



> bussin
> npx ts-node src/main.ts main.bsx

Error: ENOENT: no such file or directory, open 'main.bsx'
    at Object.openSync (node:fs:603:3)
    at readFileSync (node:fs:471:35)
    at C:\Users\Guy\Desktop\bussin\src\main.ts:26:29
    at step (C:\Users\Guy\Desktop\bussin\src\main.ts:33:23)
    at Object.next (C:\Users\Guy\Desktop\bussin\src\main.ts:14:53)
    at C:\Users\Guy\Desktop\bussin\src\main.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Guy\Desktop\bussin\src\main.ts:4:12)
    at run (C:\Users\Guy\Desktop\bussin\src\main.ts:57:12)
    at Object.<anonymous> (C:\Users\Guy\Desktop\bussin\src\main.ts:17:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'main.bsx'
}

**Comment by Symmettry** [comment]
there is no "main.bsx"
you have to specify a path to the bussin file.

e.g. if you're referring to examples/main.bsx then put ./examples/main.bsx

**Comment by Powersaj-Tech** [comment]
Im getting an issue here too, after cloning it, I get 
```
C:\Users\user>npm install bussin
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/bussin - Not found
npm ERR! 404
npm ERR! 404  'bussin@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```
I might not know how to use this and/or there is something wrong with the project.

**Comment by Powersaj-Tech** [comment]
my bad i didnt even use the correct command, however i get the error here too
```
C:\Users\user>npm run bussin
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\jimdi\package.json
npm ERR! errno -4058
npm ERR! enoent Could not read package.json: Error: ENOENT: no such file or directory, open 'C:\Users\jimdi\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in: C:\Users\user\AppData\Local\npm-cache\_logs\2023-11-22T14_52_42_457Z-debug-0.log
```

**Comment by face-hh** [comment]
> i get the error here too
> 
> ```
> C:\Users\user>npm run bussin
> npm ERR! code ENOENT
> npm ERR! syscall open
> npm ERR! path C:\Users\jimdi\package.json
> npm ERR! errno -4058
> npm ERR! enoent Could not read package.json: Error: ENOENT: no such file or directory, open 'C:\Users\jimdi\package.json'
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in: C:\Users\user\AppData\Local\npm-cache\_logs\2023-11-22T14_52_42_457Z-debug-0.log
> ```
> 
> I can confirm that bussin is there, without a doubt. But attempts to install it arent going well.

Follow what @Symmettry said:

> there is no "main.bsx"
> you have to specify a path to the bussin file.
> 
> e.g. if you're referring to examples/main.bsx then put ./examples/main.bsx
