### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Polygons1** [face-hh/bussin#3]
@face-hh why there is GeoIP?

**Comment by face-hh** [comment]
To determine the local currency symbol

**Comment by Polygons1** [comment]
I will make a RegExp for that if you want

**Comment by Polygons1** [comment]
here it is: /(؋|L|د.ج|$|€|Kz|null|ƒ|.د.ب|৳|Br|Fr|Nu.|Bs.|P|R$|лв|៛|Esc|¥|₡|kn|Kč|kr|£|Nfk|D|ლ|₵|Q|G|Ft|₹|Rp|﷼|ع.د|₪|د.ا|Sh|د.ك|с|₭|ل.ل|ل.د|ден|Ar|MK|RM|.ރ|UM|₨|₮|د.م.|MT|Ks|C$|₦|₩|ر.ع.|K|₲|S/.|₱|zł|ر.ق|lei|₽|T|Db|ر.س|дин.|Le|R|Rs|ج.س.|ЅМ|฿|T$|د.ت|m|₴|د.إ|Vt|Bs F|₫|ZK)/g

**Comment by Crelt** [comment]
shut yo stinky binky ass up

**Comment by Polygons1** [comment]
> shut yo stinky binky ass up

who?

**Comment by Polygons1** [comment]
@face-hh I added the regexp in my PR looooooooool

**Comment by GStudiosX2** [comment]
> I will make a RegExp for that if you want

you know right that its meant to be like to your local currency not like you can use any currency smh.

**Comment by Polygons1** [comment]
> > I will make a RegExp for that if you want
> 
> you know right that its meant to be like to your local currency not like you can use any currency smh.

but the problem is that GeoIP requires additional files and because of that it can't be an executable like every other language

**Comment by Polygons1** [comment]
also you only have the local currency in your keyboard (or only dollar)

**Comment by GStudiosX2** [comment]
> also you only have the local currency in your keyboard (or only dollar)

i have £ and $ lol

**Comment by Polygons1** [comment]
if your keyboard have it, that means it local I think

**Comment by face-hh** [comment]
It works as intended.

**Comment by Polygons1** [comment]
@face-hh do you want an exe or not? if yes everything is in my pr

**Comment by face-hh** [comment]
I'll take a look when I'll be home

**Comment by Polygons1** [comment]
> I'll take a look when I'll be home

touch some grass, it's ok

**Comment by GStudiosX2** [comment]
> if your keyboard have it, that means it local I think

its prob because maybe those currencies are used in different parts of UK idk

**Comment by GStudiosX2** [comment]
> > > I will make a RegExp for that if you want
> > 
> > 
> > you know right that its meant to be like to your local currency not like you can use any currency smh.
> 
> but the problem is that GeoIP requires additional files and because of that it can't be an executable like every other language

i mean you can make the build include those extra files like you would have the main exe and then the libraries with it

**Comment by Polygons1** [comment]
> > > > I will make a RegExp for that if you want
> > > 
> > > 
> > > you know right that its meant to be like to your local currency not like you can use any currency smh.
> > 
> > 
> > but the problem is that GeoIP requires additional files and because of that it can't be an executable like every other language
> 
> i mean you can make the build include those extra files like you would have the main exe and then the libraries with it probably can link them some how idk

it's not like a .jar file and to make an executable in js you need the pkg library

**Comment by GStudiosX2** [comment]
> > > > > I will make a RegExp for that if you want
> > > > 
> > > > 
> > > > you know right that its meant to be like to your local currency not like you can use any currency smh.
> > > 
> > > 
> > > but the problem is that GeoIP requires additional files and because of that it can't be an executable like every other language
> > 
> > 
> > i mean you can make the build include those extra files like you would have the main exe and then the libraries with it probably can link them some how idk
> 
> it's not like a .jar file and to make an executable in js you need the pkg library

hmm well wouldnt include node in the exe cant you use fetch from node ?

**Comment by Polygons1** [comment]
> > > > > > I will make a RegExp for that if you want
> > > > > 
> > > > > 
> > > > > you know right that its meant to be like to your local currency not like you can use any currency smh.
> > > > 
> > > > 
> > > > but the problem is that GeoIP requires additional files and because of that it can't be an executable like every other language
> > > 
> > > 
> > > i mean you can make the build include those extra files like you would have the main exe and then the libraries with it probably can link them some how idk
> > 
> > 
> > it's not like a .jar file and to make an executable in js you need the pkg library
> 
> hmm well wouldnt it include node in the exe cant you use fetch from node ?

true.... but RegExp does everything and the app is in TS, but the bundled version is in JS which node can run by default

**Comment by GStudiosX2** [comment]
> > > > > > > I will make a RegExp for that if you want
> > > > > > 
> > > > > > 
> > > > > > you know right that its meant to be like to your local currency not like you can use any currency smh.
> > > > > 
> > > > > 
> > > > > but the problem is that GeoIP requires additional files and because of that it can't be an executable like every other language
> > > > 
> > > > 
> > > > i mean you can make the build include those extra files like you would have the main exe and then the libraries with it probably can link them some how idk
> > > 
> > > 
> > > it's not like a .jar file and to make an executable in js you need the pkg library
> > 
> > 
> > hmm well wouldnt it include node in the exe cant you use fetch from node ?
> 
> true.... but RegExp does everything and the app is in TS, but the bundled version is in JS which node can run by default

node has a fetch since node v18 even before but it was experimental i dont know the exact version im not sure what geoip api you should use those.

**Comment by Polygons1** [comment]
> > > > > > > > I will make a RegExp for that if you want
> > > > > > > 
> > > > > > > 
> > > > > > > you know right that its meant to be like to your local currency not like you can use any currency smh.
> > > > > > 
> > > > > > 
> > > > > > but the problem is that GeoIP requires additional files and because of that it can't be an executable like every other language
> > > > > 
> > > > > 
> > > > > i mean you can make the build include those extra files like you would have the main exe and then the libraries with it probably can link them some how idk
> > > > 
> > > > 
> > > > it's not like a .jar file and to make an executable in js you need the pkg library
> > > 
> > > 
> > > hmm well wouldnt it include node in the exe cant you use fetch from node ?
> > 
> > 
> > true.... but RegExp does everything and the app is in TS, but the bundled version is in JS which node can run by default
> 
> node has a fetch since node v18 even before but it was experimental i dont know the exact version im not sure what geoip api you should use though.

node is 💩 I don't even have it installed because it so limited and slowwwww

**Comment by Polygons1** [comment]
> > > > > > > > > > I will make a RegExp for that if you want
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > you know right that its meant to be like to your local currency not like you can use any currency smh.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > but the problem is that GeoIP requires additional files and because of that it can't be an executable like every other language
> > > > > > > 
> > > > > > > 
> > > > > > > i mean you can make the build include those extra files like you would have the main exe and then the libraries with it probably can link them some how idk
> > > > > > 
> > > > > > 
> > > > > > it's not like a .jar file and to make an executable in js you need the pkg library
> > > > > 
> > > > > 
> > > > > hmm well wouldnt it include node in the exe cant you use fetch from node ?
> > > > 
> > > > 
> > > > true.... but RegExp does everything and the app is in TS, but the bundled version is in JS which node can run by default
> > > 
> > > 
> > > node has a fetch since node v18 even before but it was experimental i dont know the exact version im not sure what geoip api you should use though.
> > 
> > 
> > node is 💩 I don't even have it installed because it so limited and slowwwww
> 
> node is whats bundled with the exe though ?

true, it's still the same node that can run TS and doesn't allow ESM to work with CommonJS
