### ISSUE TITLE
The sus function can't compare numbers from yap("")

### ISSUE THREAD

**Issue by SzKristof97** [face-hh/bussin#39]
![image](https://github.com/face-hh/bussin/assets/47104780/d034df84-129d-4339-b835-1aa131942a70)

I'm just trying this thing out, but i can't get trough here.
When the code reaches the sus (if) function it just ignores everything and jumps directly to the last impostor (else).

![image](https://github.com/face-hh/bussin/assets/47104780/c386ca3d-9cd0-4b0f-b02d-245ffe341811)

Am i missing something? I need to convert the input into a number somehow? :D
Any idea how can i resolve this problem?

**Comment by face-hh** [comment]
This has been reported in the Discord server:

> I've done some further testing and the problem seems to be the input gotten with yap(). If I set the variable "num" to a number I know will pass, the programm runs without problems. When I use yap() however the input that is recognized as "6" for example returns null after modulo operation.

Unfortunately I don't have time to dive back into this project, if someone is willing to create a pull request with the fix, I might look into it

**Comment by SzKristof97** [comment]
Thanks for the answer anyway. :)

**Comment by Symmettry** [comment]
i had made a pull request back in november which didn’t get a response; i might be able to fix this issue later but only really if face hh cares about the pull requests anyway

**Comment by face-hh** [comment]
> i had made a pull request back in november which didn’t get a response; i might be able to fix this issue later but only really if face hh cares about the pull requests anyway 

I've checked the pull request before but always forgot to fetch to test it locally, I'll make sure to do that tomorrow
