### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by Polygons1** [face-hh/bussin#4]
1. there isn't ++ for adding + 1 to the variable
2. REPL just quit if there is an error, just implement a built in error system
3. can't fix code by moving cursor

**Comment by Polygons1** [comment]
4. can't edit objects (obj.val = "test"; throws an error)

**Comment by Polygons1** [comment]
5. doesn't exit after execution
6. enters REPL mode on error

**Comment by Polygons1** [comment]
7. backslash is not implemented

**Comment by Polygons1** [comment]
8. there is no return to functions

**Comment by Polygons1** [comment]
9. there is no arrays

**Comment by Polygons1** [comment]
10. remove GeoIP, replace all currencies with $

**Comment by Polygons1** [comment]
11. exec stdout not working
12. add stdin

**Comment by Polygons1** [comment]
13. add a null value

**Comment by Polygons1** [comment]
14. add docs

**Comment by Polygons1** [comment]
15. object.set() (if that's a thing) just freezes execution on REPL

**Comment by Polygons1** [comment]
16. types not working

**Comment by tovade** [comment]
> 16. types not working

types work in bsx but bussin isn't made as a typescript clone 💀💀💀

**Comment by Polygons1** [comment]
> > 16. types not working
> 
> types work in bsx but bussin isn't made as a typescript clone 💀💀💀

so why there is object and string and etc...?

**Comment by Polygons1** [comment]
also I recommend you to try my fork, it's better

**Comment by KaseyTheJackal** [comment]
> also I recommend you to try my fork, it's better

All you've done is make tiny changes that arguably make stuff worse

**Comment by Polygons1** [comment]
> > also I recommend you to try my fork, it's better
> 
> All you've done is make tiny changes that arguably make stuff worse

I am making stdin 😎 and removed the object from the REPL output 😎

**Comment by Polygons1** [comment]
Also I am adding more data types

**Comment by Polygons1** [comment]
> You're taking this lang too seriously its made as a meme

you don't want to rizz up with errors?

**Comment by Polygons1** [comment]
btw, I want to run this 24/7 on a server

**Comment by Polygons1** [comment]
> You're taking this lang too seriously its made as a meme

+ I want to make Bussin in Bussin so it's gonna be meme squared
