### ISSUE TITLE
No way to get character I guess ??

### ISSUE THREAD

**Issue by prakash-niroula** [face-hh/bussin#41]
So I played around with this a little bit and stumbled upon this utterly stupid problem :

```bsx
lit x be "Hello There" rn
lit firstLetter be x[0] rn
waffle(firstLetter)
```

Expected output :-
```
H
```

Given Output :-
```
Hello There
```

Tried other things like .at() .substr() but those are not implemented.
I would like this to be implemented because this is one important thing

**Comment by face-hh** [comment]
It could certainly be implemented via a native function in the environment file, if I find free time I'll add this

**Comment by Symmettry** [comment]
this is added in #43 so it should be closed ig
