### ISSUE TITLE
Cannot do -ident

### ISSUE THREAD

**Issue by Symmettry** [face-hh/bussin#56]
Something like

let x = 5;
let y = -x;

will not work

**Comment by GStudiosX2** [comment]
> Something like
> 
> let x = 5;
> let y = -x;
> 
> will not work

Can confirm `0 - x` works though

**Comment by Symmettry** [comment]
Yes you can do that, or -1 * x, etc.

**Comment by GStudiosX2** [comment]
> Yes you can do that, or -1 * x, etc.

I prefer `0 - x` but I think `- x` and `-x` should be allowed

**Comment by Symmettry** [comment]
Fixed in #55
