### ISSUE TITLE
Challenge

### ISSUE THREAD

**Issue by Polygons1** [face-hh/bussin#6]
now do what other languages do, and continue developing the language with the language

**Comment by GStudiosX2** [comment]
he would have to make this a compiled language lol

**Comment by Polygons1** [comment]
> he would have to make this a compiled language lol otherwise you'd be like `npm run bussin bussin.bs somefile.bs` lol with a compiled language you'd only have to run `bussin.bs` through bussin TS once (well if you make no mistakes)

lol, I already made a .js file that is waiting to be compiled using my build script. if you want with my bundled js file, go to my fork until @face-hh merges the PR

**Comment by Polygons1** [comment]
btw python is like Bussin, it can't compile to binary and works with REPL also. but the devs continuing to develop python with python

**Comment by GStudiosX2** [comment]
> btw python is like Bussin, it can't compile to binary and works with REPL also. but the devs continuing to develop python with python

python is made with C not python maybe some of the modules you can include is made in python though

**Comment by Polygons1** [comment]
it started with C, like how Bussin started with TypeScript
also there other languages like Ruby if I remember correctly

**Comment by Polygons1** [comment]
https://github.com/python/cpython

**Comment by GStudiosX2** [comment]
i saw its still C though the parts that are python are the standard libraries for python and some modules are still written in C

**Comment by Polygons1** [comment]
> i saw its still C though the parts that are python are the standard modules/libraries for python and some modules are still written in C

mostly misc

**Comment by Polygons1** [comment]
if you will search, I 100% sure that there is a language that coded in itself

**Comment by GStudiosX2** [comment]
alright i get it now its still technically written in C they are just generating C files using python

**Comment by Polygons1** [comment]
try looking at Zig

**Comment by Polygons1** [comment]
https://github.com/ziglang/zig

**Comment by Polygons1** [comment]
btw, LLVM (the compiler) can only be written in C++

**Comment by GStudiosX2** [comment]
zig is compiled

**Comment by Polygons1** [comment]
> zig is compiled

? (btw ? for me is like wdym?)

**Comment by GStudiosX2** [comment]
> btw, LLVM (the compiler) can only be written in C++

LLVM is used by a lot of compilers

**Comment by Polygons1** [comment]
here is a video explaining LLVM, https://www.youtube.com/watch?v=BT2Cv-Tjq7Q

**Comment by GStudiosX2** [comment]
i know what LLVM is its just that rust technically in its source apart from LLVM is mainly rust files an like lexing, parsing creating a AST rust is still doing that in rust true that it probably started in C i actually have no idea what it started in obviously cant make a language in itself from the get go

**Comment by GStudiosX2** [comment]
i mean tbh i dont care too much but like python is still made with C

**Comment by Polygons1** [comment]
but Zig is cooler 😎 because Bun made in Zig, and Bun is cool

**Comment by GStudiosX2** [comment]
i haven't used Bun but there's a lot of videos of testing Bun and seen that a lot of there claims are little falsey or there's weird little quirks and bugs but obviously probably will be fixed

**Comment by GStudiosX2** [comment]
> because Bun is not released to Windows yet 🤓

it has a very beta windows lmfao probably not worth using it yet but yeah

**Comment by Polygons1** [comment]
> > because Bun is not released to Windows yet 🤓
> 
> it has a very beta windows lmfao probably not worth using it yet but yeah

I know that 🤓

**Comment by Polygons1** [comment]
btw I will make Bussin with Bussin
