### ISSUE TITLE
Problem with ">" and "<" signs.

### ISSUE THREAD

**Issue by viliRocha** [face-hh/bussin#61]
For some reason the greater than and Lesser than signs do not support negative numbers. There are also no "=>" and "<=" signs which are important to have.

**Comment by Symmettry** [comment]
Can you give an example? It works fine on my end. The >= and <= signs aren't needed. We at bussin believe you should be explicit and have good clarity with your code, and so you must do if(x > 5 || x == 5) to show you're meaning both.

**Comment by viliRocha** [comment]
At the moment I can't really test this programming language to give you an exact snippet of code that gives me the error, but it was something similar to that:
let numbers = [13, 5, 7, 200, 3, 7.9];

fn put_in_order() {
        for (let i = 1; i < 6; i++) {
            let current = numbers[i];
            let j = i - 1;

            for (j; j >= 0 && numbers[j] > current; j--) {
                numbers[j + 1] = numbers[j]
            }
        
            numbers[j + 1] = current;
        }
}

put_in_order()
println(numbers)

This code is a simple algorithm to put the numbers in the array in the ascending order. Other observations I would like to give are that bussin currently seems to not have while loops and also its repl is outdated as the programming language is in its v1.7 and it shows as v1.0, lastly I Just think It ia important to have .length Native functions as they ARE Very important for algorithms like that.

**Comment by viliRocha** [comment]
> Can you give an example? It works fine on my end. The >= and <= signs aren't needed. We at bussin believe you should be explicit and have good clarity with your code, and so you must do if(x > 5 || x == 5) to show you're meaning both.

**Comment by Symmettry** [comment]
> At the moment I can't really test this programming language to give you an exact snippet of code that gives me the error, but it was something similar to that: let numbers = [13, 5, 7, 200, 3, 7.9];
> 
> fn put_in_order() { for (let i = 1; i < 6; i++) { let current = numbers[i]; let j = i - 1;
> 
> ```
>         for (j; j >= 0 && numbers[j] > current; j--) {
>             numbers[j + 1] = numbers[j]
>         }
>     
>         numbers[j + 1] = current;
>     }
> ```
> 
> }
> 
> put_in_order() println(numbers)
> 
> This code is a simple algorithm to put the numbers in the array in the ascending order. Other observations I would like to give are that bussin currently seems to not have while loops and also its repl is outdated as the programming language is in its v1.7 and it shows as v1.0, lastly I Just think It ia important to have .length Native functions as they ARE Very important for algorithms like that.

this is esoteric language.

while() isn't needed.

the repl version is 1.0, not the programming language. trust

string.len("hello") iirc, or it might just be len() i forgot

**Comment by Symmettry** [comment]
> At the moment I can't really test this programming language to give you an exact snippet of code that gives me the error, but it was something similar to that: let numbers = [13, 5, 7, 200, 3, 7.9];
> 
> fn put_in_order() { for (let i = 1; i < 6; i++) { let current = numbers[i]; let j = i - 1;
> 
> ```
>         for (j; j >= 0 && numbers[j] > current; j--) {
>             numbers[j + 1] = numbers[j]
>         }
>     
>         numbers[j + 1] = current;
>     }
> ```
> 
> }
> 
> put_in_order() println(numbers)
> 
> This code is a simple algorithm to put the numbers in the array in the ascending order. Other observations I would like to give are that bussin currently seems to not have while loops and also its repl is outdated as the programming language is in its v1.7 and it shows as v1.0, lastly I Just think It ia important to have .length Native functions as they ARE Very important for algorithms like that.

Doesn't seem to be an issue with the < and > symbols.

**Comment by viliRocha** [comment]
I'm sorry, it looks like it was an issue I was having in my own modified version of Bussin that does not exist in the official one, I will close this issue now. The only thing I'd like to suggest is writing all of the language's features in the README file, such as not having while loops and not having the ">=" and "<=" signs. It would be also great to have more native function examples in the main.bs file. And I think that's all, Bussin great and you guys did a great job with it!
