### ISSUE TITLE
Handle strings in computed values

### ISSUE THREAD

**Issue by hueychen27** [face-hh/bussin#62]
Your code accepts `obj[prop]`, and the `prop` identifier is not evaluated and treated like a string. This disallows putting variables as the computed value. The right code to accept would be `obj["prop"]`.

**Comment by Symmettry** [comment]
[] is for arrays only.

let x = [1,2,3];
let y = 2;
println(x[y])

This runs perfectly fine, outputting "3"

If you're using an object, it is objects.get(obj, blablabla)

See we at bussin think that this looks cool and aren't too lazy to fix the bug with [].

**Comment by hueychen27** [comment]
Good job.
