### ISSUE TITLE
Regional currency symbol not following typographical norms for the euro symbol

### ISSUE THREAD

**Issue by theskyblockman** [face-hh/bussin#7]
https://github.com/face-hh/bussin/blob/6b2a504f73e5d5e685f6e92d8a59adc608ab49ea/README.md?plain=1#L46C38-L46C38

The correct way to use the euro sign would be: 
```rs
waffle(format("Hello, {}€", "World"))
```
Our competitors like DreamBerd already have this feature. So must we.

**Comment by Polygons1** [comment]
I fixed it, just wait until he merges my PR

**Comment by face-hh** [comment]
> https://github.com/face-hh/bussin/blob/6b2a504f73e5d5e685f6e92d8a59adc608ab49ea/README.md?plain=1#L46C38-L46C38
> 
> The correct way to use the euro sign would be: ```rs
> waffle(format("Hello, {}€", "World"))
> ```
> Our competitors like DreamBerd already have this feature. So must we.

That is truly shameful for treating such a groundbreaking issue as disparage. I will make sure to fix it.

**Comment by Polygons1** [comment]
> > https://github.com/face-hh/bussin/blob/6b2a504f73e5d5e685f6e92d8a59adc608ab49ea/README.md?plain=1#L46C38-L46C38
> > The correct way to use the euro sign would be: ```rs
> > waffle(format("Hello, {}€", "World"))
> > ```
> > Our competitors like DreamBerd already have this feature. So must we.
> > ```
> 
> I am truly shameful for treating such a groundbreaking issue as disparage. I will make sure to fix it.

LOL I already fixed it 😂

**Comment by DrPeeper228** [comment]
Also the Russian rub symbol also should work like that
